In [48]:
import pandas as pd
pd.set_option('display.max_columns', None) #show all columns
pd.set_option('max_colwidth',None)
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [48]:
data=pd.read_csv('result/final_tableV10.csv')
data['first_careunit']=data['first_careunit'].map({'MICU':0, 'CCU':1, 'NICU':2, 'SICU':3, 'TSICU':4, 'CSRU':5})
data['ethnicity']=data['ethnicity'].map({'WHITE':1, 'ASIAN':2, 'BLACK/AFRICAN AMERICAN':3,
       'UNKNOWN/NOT SPECIFIED':0, 'HISPANIC OR LATINO':1,
       'PATIENT DECLINED TO ANSWER':0, 'MULTI RACE ETHNICITY':4, 'OTHER':0,
       'ASIAN - ASIAN INDIAN':2, 'HISPANIC/LATINO - HONDURAN':1,
       'BLACK/HAITIAN':3, 'UNABLE TO OBTAIN':0, 'ASIAN - VIETNAMESE':2,
       'WHITE - BRAZILIAN':1, 'WHITE - RUSSIAN':1, 'ASIAN - KOREAN':2,
       'ASIAN - CHINESE':2, 'WHITE - OTHER EUROPEAN':1,
       'HISPANIC/LATINO - PUERTO RICAN':1, 'ASIAN - CAMBODIAN':2})

In [49]:
data['group']=0
data.loc[data[(data['gender']==1) & (data['uric_acid.csv']>=7)].index, 'group']=1
data.loc[data[(data['gender']==0) & (data['uric_acid.csv']>=6)].index, 'group']=1

In [49]:
data=pd.read_csv('result/finaltable.csv')
data.drop(['Unnamed: 0'], axis=1,inplace=True)
data['low_group']=0
data['high_group']=0
data.loc[data[data['group']==1].index,'high_group']=1
data.loc[data[data['group']==0].index,'low_group']=1

In [50]:
data['age_class']=0
data['BMI_class']=0

In [51]:
data.loc[data[data['age']>=65].index, 'age_class']=1

In [54]:
data.loc[data[(data['BMI']>=18.5)&(data['BMI']<=24.9)].index, 'BMI_class']=1
data.loc[data[(data['BMI']>=24.9)].index, 'BMI_class']=2

In [55]:
data

,subject_id,hadm_id,icustay_id,ethnicity,gender,first_careunit,los,dob_h,dod_h,admittime_h,dischtime_h,intime_h,outtime_h,hospital_mortality,30_mortality,90_mortality,365_mortality,age,sofa,vasopressin,sapsii,heartrate_mean,resprate_mean,tempc_mean,hemoglobin_mean,lactate_mean,pco2_mean,ph_mean,po2_mean,potassium_mean,CKD.csv,COPD.csv,coronary heart disease.csv,diabetes.csv,hypertension.csv,liver disease.csv,sepsis.csv,creatinine.csv,glucose.csv,neutrophils.csv,platelet.csv,potassium.csv,sodium.csv,urea nitrogen.csv,uric_acid.csv,WBC.csv,albumin,MAP,BMI,group,AKI,surviving_time,low_group,high_group,age_class,BMI_class
0,3,145834,211552.0,1,1,0,6.0646,572208.0,1248696.0,1.243027e+06,1.243286e+06,1.243027e+06,1.243173e+06,0.0,0.0,0.0,1.0,76.577531,7,0.0,79,111.785714,17.361111,37.002881,7.8,4.871429,31.153846,7.356429,142.538462,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.4,140.0,87.00000,190.0,4.4,138.0,41.0,10.3,11.3,1.800000,71.466667,30.187677,1,0.0,236.202778,0,1,1,2
1,38,185910,248910.0,1,1,1,25.5485,1145400.0,NaN,1.811088e+06,1.811700e+06,1.811088e+06,1.811702e+06,0.0,0.0,0.0,0.0,75.991837,6,0.0,49,105.585366,24.325000,36.522222,12.5,2.800000,43.000000,7.320000,38.000000,4.324133,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.6,137.0,63.00000,112.0,4.2,139.0,55.0,5.9,14.0,2.700000,73.000000,26.012784,0,0.0,4000.000000,1,0,1,2
2,101,175533,233111.0,2,1,0,9.8919,1354800.0,2075592.0,2.075227e+06,2.075605e+06,2.075227e+06,2.075464e+06,1.0,1.0,1.0,1.0,82.240483,7,0.0,54,87.034483,23.135135,37.990741,11.0,5.825000,34.500000,7.278750,132.250000,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.9,207.0,79.00000,243.0,3.9,144.0,15.0,4.9,10.9,2.841882,76.818182,30.493316,0,0.0,15.225000,1,0,1,2
3,159,156461,259440.0,3,1,2,89.7806,1686888.0,NaN,1.686909e+06,1.689064e+06,1.686909e+06,1.689064e+06,0.0,0.0,0.0,0.0,0.002405,14,0.0,48,147.760000,20.144916,36.952345,10.8,2.835558,36.750000,7.312500,67.250000,4.324133,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.7,52.0,34.00000,101.0,2.8,127.0,5.0,5.3,4.2,2.841882,78.887362,3.546713,0,0.0,4000.000000,1,0,0,0
4,191,142081,285720.0,2,1,0,4.2111,1429848.0,NaN,2.033657e+06,2.033922e+06,2.033660e+06,2.033761e+06,0.0,0.0,0.0,0.0,68.928282,4,0.0,40,67.153846,15.593750,36.317460,12.6,2.020000,34.900000,7.310000,169.500000,3.625000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.8,352.0,88.00000,230.0,3.9,137.0,70.0,4.6,7.8,3.200000,84.884615,30.493316,0,0.0,4000.000000,1,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1109,99067,130940,204903.0,1,1,1,15.8199,1103688.0,1794912.0,1.794554e+06,1.794930e+06,1.794554e+06,1.794933e+06,1.0,1.0,1.0,1.0,78.865931,2,1.0,47,113.333333,19.884615,35.900000,16.2,2.835558,39.684847,7.359693,132.548682,4.324133,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.3,105.0,83.00000,334.0,5.1,128.0,53.0,7.7,19.7,3.800000,71.724638,23.473057,1,1.0,14.936111,0,1,1,1
1110,99299,173241,279468.0,0,0,0,0.9535,1097736.0,NaN,1.762917e+06,1.762985e+06,1.762917e+06,1.762940e+06,0.0,0.0,0.0,0.0,75.933913,3,0.0,41,83.727273,14.909091,35.955556,10.8,2.100000,39.684847,7.359693,132.548682,4.200000,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.8,206.0,71.45625,188.0,3.9,142.0,15.0,6.1,4.2,2.841882,102.787879,30.493316,1,0.0,4000.000000,0,1,1,2
1111,99403,150097,209909.0,1,1,0,9.0572,1074240.0,NaN,1.654287e+06,1.654649e+06,1.654287e+06,1.654504e+06,0.0,0.0,0.0,0.0,66.215401,4,0.0,31,91.562500,20.217391,36.311594,7.5,2.050000,39.000000,7.510000,36.000000,4.324133,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.6,214.0,5.00000,11.0,3.8,131.0,22.0,5.5,38.9,2.841882,88.166667,30.493316,0,1.0,4000.000000,1,0,1,2
1112,99562,129689,246497.0,1,1,0,2.0713,1411248.0,1959312.0,1.955583e+06,1.955965e+06,1.955583e+06,1.955633e+06,0.0,0.0,0.0,1.0,62.138727,7,0.0,35,93.740741,21.037037,36.740741,8.1,1.100000,35.333333,7.413333,121.666667,5.800000,1.0,0.0,1.0,0.0,0.0,0.0,1.0,2.6,200.0,92.50000,125.0,3.8,140.0,42.0,5.2,23.6,2.800000,88.652778,23.632184,0,0.0,155.365972,1,0,0,1
1113,99847,155024,219261.0,1,0,0,3.7463,1364424.0,2034696.0,2.027375e+06,2.027799e+06,2.027376e+06,2.027466e+06,0.0,0.0,0.0,1.0,75.679437,7,0.0,49,114.586207,24.793103,36.194444,8.4,1.500000,33.000000,7.460000,58.000000,4.324133,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.5,186.0,88.00000,36.0,4.2,141.0,27.0,6.1,0.8,3.900000,90.964286,22.905601,1,0.0,305.022917,0,1,1,1

In [56]:
data.to_csv('result/finaltableV2.csv',index=False)

In [58]:
data[data['age']>=18].to_csv('result/finaltableV2.csv',index=False)