In [1]:
import psycopg2
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_columns', None) #show all columns
pd.set_option('max_colwidth',None)

In [2]:
surgery=pd.read_csv(os.path.dirname(os.getcwd())+'/data/original data/surgery.csv')

In [3]:
def search_table(s='*', f='admissions', w='', like='', download_as=''):
    temp=s.lower()
    for i in temp:
        if i>"z" or i<"a":
            assert "TypeError"
    del temp
    conn = psycopg2.connect(database="mimic", user="postgres",
                            password="pandora", host="127.0.0.1", port="5432")
    cursor = conn.cursor()
    if (w!='')&(like!=''):
        cursor.execute("select " + s + " from mimiciii." + f +' where '+ w +
                       ' like ' + "'%"+ like +"%'")
    elif (w!='')&(like=='') :
        cursor.execute("select " + s + " from mimiciii." + f +' where '+ w)
    else:
        cursor.execute("select " + s + " from mimiciii." + f)
    table = cursor.fetchall()
    if(len(table)!=0):
        colnames = [desc[0] for desc in cursor.description]
        columns = cursor.fetchall()
        cursor.close()
        conn.close()
        columns=pd.DataFrame(columns)
        table=pd.DataFrame(table)
        table.columns=colnames
    if(download_as!=''):
        table.to_csv(os.path.dirname(os.getcwd())+'/data/download data/'+download_as+'.csv', index=False)
    return table

In [4]:
def searchSurgery(surgery_name, download_as=''):
    result=surgery
    index=result['long_title'].str.contains(surgery_name)
    result=surgery.loc[index[index.values==True].index,:]
    if download_as!='':
        result.to_csv(os.path.dirname(os.getcwd())+'/data/download data/'+download_as+'.csv', index=False)
    print('there are', len(result['long_title'].unique()), 'related surgery of', surgery_name, ':\n', 
          result['long_title'].unique())
    return result

In [5]:
res=searchSurgery(surgery_name='kidney transplantation', download_as='')
res

there are 1 related surgery of kidney transplantation :
 ['Other kidney transplantation']

,row_id,subject_id,hadm_id,seq_num,icd9_code,short_title,long_title
11,91635,6,107064,1,5569.0,Kidney transplant NEC,Other kidney transplantation
5465,102461,998,171544,1,5569.0,Kidney transplant NEC,Other kidney transplantation
5694,71674,1027,105588,1,5569.0,Kidney transplant NEC,Other kidney transplantation
5800,96275,1047,137911,1,5569.0,Kidney transplant NEC,Other kidney transplantation
8981,126672,1709,176360,1,5569.0,Kidney transplant NEC,Other kidney transplantation
...,...,...,...,...,...,...,...
246200,191233,98851,105014,1,5569.0,Kidney transplant NEC,Other kidney transplantation
246324,217403,98994,178949,1,5569.0,Kidney transplant NEC,Other kidney transplantation
247195,210477,99503,146847,1,5569.0,Kidney transplant NEC,Other kidney transplantation
247413,173248,99650,158023,1,5569.0,Kidney transplant NEC,Other kidney transplantation
247768,204862,99923,192053,3,5569.0,Kidney transplant NEC,Other kidney transplantation