In [141]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import numpy as np
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
import pandas_profiling as ppf
pd.set_option('display.max_columns', None) #show all columns
pd.set_option('max_colwidth',None)

In [142]:
#to set a drop_list to drop the columns in this list
drop_list=['glucose_min','glucose_max','wbc_min','wbc_max','platelet_max','platelet_min',
          'potassium_min','potassium_max','sodium_min','sodium_max','creatinine_min','creatinine_max',
          'bun_min','bun_max','hospital_expire_flag','has_chartevents_data',
          'expire_flag','admission_type','admission_location','discharge_location',
          'insurance','language','religion','marital_status','diagnosis','dbsource',
          'last_careunit','vasopressin_duration','sirs','apsiii','rrt','urineoutput',
          'lods','aniongap_min','aniongap_max','bands_min','bands_max', 'bicarbonate_min', 'bicarbonate_max', 'bilirubin_min',
       'bilirubin_max', 'chloride_min', 'chloride_max', 'hematocrit_min',
       'hematocrit_max','ptt_min', 'ptt_max', 'inr_min', 'inr_max', 'pt_min',
       'pt_max','spo2_mean', 'mingcs', 'infection',
       'explicit_sepsis', 'organ_dysfunction', 'mech_vent', 'angus',
       'aado2_mean', 'baseexcess_mean', 'bicarbonate_mean', 'totalco2_mean',
       'carboxyhemoglobin_mean', 'chloride_mean', 'calcium_mean', 'peep_mean',
          'methemoglobin_mean', 'o2flow_mean', 'fio2_mean',
       'so2_mean','hematocrit_mean', 'intubated_mean','requiredo2_mean', 'tidalvolume_mean',
          'sodium_mean','C-reactive protein.csv','lymphocyte_count.csv','glucose_mean',
          'lactate_min','lactate_max','temperature_mean']

In [143]:
final_tableV8=pd.read_csv('result/final_tableV5.csv')
final_tableV8.drop(drop_list, axis=1, inplace=True)
#remove children samples
#final_tableV8.drop(final_tableV8[final_tableV8['age']<18].index, inplace=True)#drop samples whose age is lesser than 18

In [144]:
final_tableV8['hemoglobin_mean']=(final_tableV8['hemoglobin_min']+final_tableV8['hemoglobin_min'])/2
final_tableV8['albumin']=(final_tableV8['albumin_max']+final_tableV8['albumin_min'])/2
final_tableV8['MAP']=((1/3)*final_tableV8['sysbp_mean'] + (2/3)*final_tableV8['diasbp_mean'])
final_tableV8.drop(['hemoglobin_min','hemoglobin_max','albumin_max','albumin_min',
                   'sysbp_mean','diasbp_mean'], axis=1, inplace=True)
#missing_values=list(final_tableV8.columns[20:22])+list(final_tableV8.columns[37:45])+list(final_tableV8.columns[51:])

In [145]:
#use winsorize to deal with outlier
def winsorize(data, percentage_one=0.01, percentage_two=0.99, show=False):
    if show==True:
        plt.figure(figsize=(5,5), dpi=300)
        ax1=plt.subplot(121)
        plt.hist(data, bins=100)
    count1=len(data)
    lower_bound=data.quantile(percentage_one)
    upper_bound=data.quantile(percentage_two)
    count2=len(data[data<lower_bound])+len(data[data>upper_bound])
    data[data<lower_bound]=lower_bound
    data[data>upper_bound]=upper_bound
    
    if show==True:
        print('', data.name, ':\n', 'lower bound is', lower_bound,'\n',
          'upeer bound is', upper_bound,'\n', 
          'totally dealt with',count2, 'of', count1, '(', (count2/count1)*100, '%)', '\n')
        ax2=plt.subplot(122)
        plt.hist(data, bins=100)
    
    
def regression(name1,name2):
    name_x=name1
    name_y=name2
    regData=final_tableV8[final_tableV8[name_x].notnull() & final_tableV8[name_y].notnull()]
    x=regData[name_x].values.reshape(-1,1)
    y=regData[name_y].values.reshape(-1,1)
    reg=LinearRegression()
    reg.fit(x,y)
    x2=np.linspace(x.min(), x.max(), num=10)
    y2 = reg.predict(x2.reshape(-1,1))
    fig = plt.figure()
    ax1 = fig.add_subplot(1,1,1)
    ax1.scatter(x,y, s=2)
    ax1.plot(x2, y2, c='black')
    plt.show()
    print('R^2 is', reg.score(x,y))

In [146]:
winsorize(final_tableV8['age'], 0.00, 0.948)
winsorize(final_tableV8['height_first'], 0.01, 0.99)
winsorize(final_tableV8['weight_first'], 0.01, 0.99)

c:\programs\python project\venv\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
c:\programs\python project\venv\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

In [147]:
def meanFill(dataframe, variables_list, show=False):
    for i in variables_list:
        dataframe[i].fillna(dataframe[i].mean(),inplace=True)


def fill(dataframe, variables_list, variables_y, parameters, model, show=False):
    for i in variables_y:
        if show==True:
            plt.figure(figsize=(10,10), dpi=300)
            ax1=plt.subplot(121)
            plt.hist(dataframe[i], bins=100)
        clf=GridSearchCV(model, parameters, cv=5)
        X=dataframe[dataframe[i].notnull()][variables_list]
        y=dataframe[dataframe[i].notnull()][i]
        clf.fit(X, y)
        scores=clf.score(X, y)
        #scores = cross_val_score(estimator=model, X=dataframe[variables_list], y=dataframe['hospital_mortality'], cv=5,scoring = "neg_mean_absolute_error")
        #train_score=model.score(dataframe[variables_list], dataframe['hospital_mortality'])

        print('the best model is:', clf.best_estimator_, 'with best score', clf.best_score_)
        print('mean test scores are', clf.cv_results_['mean_test_score'])
        fillX=dataframe[dataframe[i].isnull()][variables_list]
        dataframe.loc[dataframe[dataframe[i].isnull()].index, i]=clf.predict(fillX)
        if show==True:
            ax2=plt.subplot(122)
            plt.hist(dataframe[i], bins=100)
            plt.show()

In [148]:
final_tableV8.describe()

,subject_id,hadm_id,icustay_id,los,height_first,weight_first,dob_h,dod_h,admittime_h,dischtime_h,intime_h,outtime_h,hospital_mortality,30_mortality,90_mortality,365_mortality,age,sofa,vasopressin,sapsii,heartrate_mean,resprate_mean,tempc_mean,hemoglobin_mean,lactate_mean,pco2_mean,ph_mean,po2_mean,potassium_mean,CKD.csv,COPD.csv,coronary heart disease.csv,diabetes.csv,hypertension.csv,liver disease.csv,sepsis.csv,creatinine.csv,glucose.csv,neutrophils.csv,platelet.csv,potassium.csv,sodium.csv,urea nitrogen.csv,uric_acid.csv,WBC.csv,albumin,MAP
count,46476.000000,46476.000000,46476.000000,46467.000000,22993.000000,39986.000000,4.647600e+04,1.573700e+04,4.647600e+04,4.647600e+04,4.647600e+04,4.646700e+04,46476.000000,46476.000000,46476.000000,46476.000000,46476.000000,46476.000000,46476.000000,46476.000000,44503.000000,37880.000000,37216.000000,44586.000000,24594.000000,28891.000000,29939.000000,28892.000000,21209.000000,46476.000000,46476.000000,46476.000000,46476.000000,46476.000000,46476.000000,46476.000000,38378.000000,38070.000000,21205.000000,42273.000000,40362.000000,40335.000000,38387.000000,2058.000000,42260.000000,13545.000000,37900.000000
mean,34440.347147,150030.444832,250113.391643,5.042017,147.493962,71.185480,1.130401e+06,1.687801e+06,1.673011e+06,1.673255e+06,1.673033e+06,1.673170e+06,0.096566,0.128303,0.157006,0.211701,52.857156,3.776573,0.034599,31.584302,93.207330,18.652800,36.847679,11.235072,2.430019,41.790480,7.368032,164.282134,4.240913,0.063452,0.016718,0.234895,0.212540,0.379744,0.007187,0.276917,1.262450,144.266562,72.075364,223.616968,4.214689,138.386290,23.627765,5.899854,12.438075,3.211152,80.322297
std,28335.573385,28898.392819,28894.614584,10.317132,48.861030,32.703686,5.635215e+05,2.559657e+05,2.555728e+05,2.555742e+05,2.555726e+05,2.555780e+05,0.295369,0.334430,0.363810,0.408518,28.685928,3.129584,0.182763,15.024448,24.575460,3.943815,0.633751,3.247058,1.826266,9.248186,0.072913,86.823585,0.725754,0.243777,0.128215,0.423938,0.409109,0.485328,0.084469,0.447480,1.376167,70.114974,19.269046,108.920049,0.799519,4.714195,19.727989,3.331848,9.428430,0.707448,11.131877
min,2.000000,100001.000000,200003.000000,0.000100,33.000000,0.200000,-1.398144e+06,1.231296e+06,1.231028e+06,1.231073e+06,1.231028e+06,1.231047e+06,0.000000,0.000000,0.000000,0.000000,0.000007,0.000000,0.000000,0.000000,30.000000,7.000000,30.000000,1.200000,0.300000,10.000000,6.650000,14.000000,0.900000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,0.000000,5.000000,0.700000,83.000000,0.000000,0.200000,0.100000,1.000000,19.388889
25%,12291.750000,125017.750000,225152.750000,1.067100,154.940000,60.000000,9.086580e+05,1.466064e+06,1.452214e+06,1.452432e+06,1.452224e+06,1.452298e+06,0.000000,0.000000,0.000000,0.000000,38.559591,1.000000,0.000000,21.000000,76.229670,15.916667,36.468254,8.900000,1.400000,36.750000,7.333333,94.800000,3.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.700000,106.000000,64.000000,152.000000,3.700000,136.000000,12.000000,3.400000,8.000000,2.700000,72.600000
50%,24663.500000,149980.000000,250130.500000,2.027800,167.640000,75.000000,1.196784e+06,1.686816e+06,1.673589e+06,1.673740e+06,1.673592e+06,1.673656e+06,0.000000,0.000000,0.000000,0.000000,60.563219,3.000000,0.000000,31.000000,87.461538,18.000000,36.822222,10.700000,1.933333,40.750000,7.375000,150.666667,4.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.900000,129.000000,77.600000,209.000000,4.100000,139.000000,17.000000,5.200000,11.100000,3.200000,78.795926
75%,55523.750000,175138.250000,275128.500000,4.394550,177.800000,90.000000,1.445676e+06,1.910712e+06,1.894735e+06,1.894895e+06,1.894738e+06,1.894879e+06,0.000000,0.000000,0.000000,0.000000,75.602780,6.000000,0.000000,40.000000,103.966092,20.710526,37.214286,12.900000,2.800000,45.000000,7.412500,221.229167,4.600000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.200000,162.000000,86.000000,277.000000,4.600000,141.000000,27.000000,7.600000,15.100000,3.700000,86.818765
max,99999.000000,199999.000000,299999.000000,171.622700,193.040000,153.515000,2.117472e+06,2.204064e+06,2.179471e+06,2.179623e+06,2.179477e+06,2.179518e+06,1.000000,1.000000,1.000000,1.000000,88.104791,22.000000,1.000000,118.000000,244.800000,45.500000,40.833333,23.800000,25.540000,182.000000,7.690000,630.000000,36.982353,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,46.600000,2440.000000,100.000000,2292.000000,19.600000,180.000000,270.000000,21.100000,572.500000,6.300000,147.360000

In [149]:
final_tableV8['los'].fillna(final_tableV8['los'].mean(), inplace=True)
#final_tableV8['height_first'].fillna(final_tableV8['height_first'].mean(), inplace=True)
final_tableV8['weight_first'].fillna(final_tableV8['weight_first'].mean(), inplace=True)
#variables_list=final_tableV8.columns[29:]
#meanFill(final_tableV8, missing_values)
final_tableV8['gender']=final_tableV8['gender'].map(lambda x:1 if x=='M' else 0)
divide=final_tableV8['height_first']/100
final_tableV8['BMI']=final_tableV8['weight_first']/(divide*divide)
final_tableV8.drop(['weight_first','height_first'], axis=1, inplace=True)

In [150]:
data=final_tableV8[final_tableV8['sepsis.csv']==1]
data=data[data['uric_acid.csv'].notnull()]

In [151]:
data.describe()

,subject_id,hadm_id,icustay_id,gender,los,dob_h,dod_h,admittime_h,dischtime_h,intime_h,outtime_h,hospital_mortality,30_mortality,90_mortality,365_mortality,age,sofa,vasopressin,sapsii,heartrate_mean,resprate_mean,tempc_mean,hemoglobin_mean,lactate_mean,pco2_mean,ph_mean,po2_mean,potassium_mean,CKD.csv,COPD.csv,coronary heart disease.csv,diabetes.csv,hypertension.csv,liver disease.csv,sepsis.csv,creatinine.csv,glucose.csv,neutrophils.csv,platelet.csv,potassium.csv,sodium.csv,urea nitrogen.csv,uric_acid.csv,WBC.csv,albumin,MAP,BMI
count,1114.000000,1114.000000,1114.000000,1114.000000,1114.000000,1.114000e+03,7.430000e+02,1.114000e+03,1.114000e+03,1.114000e+03,1.114000e+03,1114.000000,1114.000000,1114.000000,1114.000000,1114.000000,1114.000000,1114.000000,1114.000000,1100.000000,1091.000000,1086.000000,1109.000000,895.000000,943.000000,970.000000,943.000000,647.000000,1114.000000,1114.000000,1114.000000,1114.000000,1114.000000,1114.000000,1114.0,1114.000000,1112.000000,960.000000,1114.000000,1114.000000,1114.00000,1113.000000,1114.000000,1111.000000,696.000000,1095.000000,613.000000
mean,30121.527828,148941.656194,249871.753142,0.581688,10.455977,1.063377e+06,1.676842e+06,1.665315e+06,1.665937e+06,1.665388e+06,1.665639e+06,0.250449,0.321364,0.381508,0.492819,63.196364,6.374327,0.116697,44.051167,91.842183,20.144916,36.952345,9.405951,2.835558,39.684847,7.359693,132.548682,4.324133,0.087074,0.016158,0.153501,0.251346,0.337522,0.015260,1.0,1.880521,152.035971,71.456250,190.991023,4.180072,137.70377,36.062893,6.125135,15.615365,2.841882,78.887362,30.493316
std,27171.905518,29282.306759,28830.771634,0.493504,13.834975,4.289871e+05,2.525832e+05,2.556294e+05,2.556176e+05,2.556261e+05,2.556197e+05,0.433466,0.467210,0.485975,0.500173,16.796661,3.426930,0.321203,14.935082,17.774694,4.869919,0.767290,2.029543,2.194835,9.353749,0.074832,59.759957,0.783416,0.282070,0.126140,0.360632,0.433982,0.473077,0.122642,0.0,2.014692,79.682067,24.717687,136.172490,0.819658,5.68381,29.176429,3.527741,25.542278,0.659662,11.403367,38.267650
min,3.000000,100095.000000,200035.000000,0.000000,0.024900,-1.384152e+06,1.233312e+06,1.232547e+06,1.232923e+06,1.232584e+06,1.232618e+06,0.000000,0.000000,0.000000,0.000000,0.000698,0.000000,0.000000,6.000000,48.516129,7.000000,32.622222,2.900000,0.400000,16.000000,7.040000,25.250000,1.900000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.200000,26.000000,0.000000,5.000000,1.900000,103.00000,2.000000,0.200000,0.100000,1.000000,47.495935,2.947041
25%,10343.000000,123922.750000,224118.750000,0.000000,2.168050,8.735100e+05,1.465380e+06,1.447847e+06,1.448585e+06,1.447847e+06,1.447948e+06,0.000000,0.000000,0.000000,0.000000,52.620803,4.000000,0.000000,34.000000,79.273923,16.627418,36.429068,8.100000,1.500000,34.183333,7.315000,89.000000,3.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.800000,109.000000,67.000000,91.250000,3.600000,135.00000,16.000000,3.400000,6.700000,2.400000,71.078632,24.170242
50%,20845.500000,148205.000000,250554.500000,1.000000,5.124550,1.092240e+06,1.666872e+06,1.655375e+06,1.655728e+06,1.655376e+06,1.655620e+06,0.000000,0.000000,0.000000,0.000000,65.237623,6.000000,0.000000,42.000000,90.637681,19.576923,36.896446,9.200000,2.166667,38.769231,7.363333,121.400000,4.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.200000,133.000000,80.200000,162.500000,4.000000,138.00000,27.000000,5.400000,11.300000,2.800000,76.946581,27.661594
75%,44190.000000,174754.750000,274595.750000,1.000000,13.609325,1.334400e+06,1.887132e+06,1.889690e+06,1.890427e+06,1.889690e+06,1.890092e+06,0.750000,1.000000,1.000000,1.000000,76.589688,8.000000,0.000000,52.000000,104.263333,22.952753,37.442460,10.500000,3.483333,43.333333,7.408136,165.222222,4.725000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.0,2.100000,172.250000,87.700000,256.000000,4.600000,141.00000,47.000000,8.200000,17.600000,3.250000,85.416667,32.024857
max,99847.000000,199976.000000,299903.000000,1.000000,153.928000,2.005608e+06,2.186136e+06,2.116958e+06,2.117104e+06,2.116958e+06,2.116993e+06,1.000000,1.000000,1.000000,1.000000,88.104791,21.000000,1.000000,110.000000,150.387097,42.200000,39.619047,17.000000,18.983333,125.000000,7.570000,509.000000,7.050000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,24.600000,1075.000000,98.100000,856.000000,7.600000,176.00000,218.000000,21.100000,471.700000,5.100000,129.947368,945.821855

In [135]:
data.columns

Index(['subject_id', 'hadm_id', 'icustay_id', 'ethnicity', 'gender',
       'first_careunit', 'los', 'dob_h', 'dod_h', 'admittime_h', 'dischtime_h',
       'intime_h', 'outtime_h', 'hospital_mortality', '30_mortality',
       '90_mortality', '365_mortality', 'age', 'sofa', 'vasopressin', 'sapsii',
       'heartrate_mean', 'resprate_mean', 'tempc_mean', 'hemoglobin_mean',
       'lactate_mean', 'pco2_mean', 'ph_mean', 'po2_mean', 'potassium_mean',
       'CKD.csv', 'COPD.csv', 'coronary heart disease.csv', 'diabetes.csv',
       'hypertension.csv', 'liver disease.csv', 'sepsis.csv', 'creatinine.csv',
       'glucose.csv', 'neutrophils.csv', 'platelet.csv', 'potassium.csv',
       'sodium.csv', 'urea nitrogen.csv', 'uric_acid.csv', 'WBC.csv',
       'albumin', 'MAP', 'BMI'],
      dtype='object')

In [136]:
missing_values=['los','hospital_mortality', '30_mortality',
       '90_mortality', '365_mortality', 'age', 'sofa', 'vasopressin', 'sapsii',
       'heartrate_mean', 'resprate_mean', 'tempc_mean', 'hemoglobin_mean',
       'lactate_mean', 'pco2_mean', 'ph_mean', 'po2_mean', 'potassium_mean',
       'CKD.csv', 'COPD.csv', 'coronary heart disease.csv', 'diabetes.csv',
       'hypertension.csv', 'liver disease.csv', 'sepsis.csv', 'creatinine.csv',
       'glucose.csv', 'neutrophils.csv', 'platelet.csv', 'potassium.csv',
       'sodium.csv', 'urea nitrogen.csv', 'uric_acid.csv', 'WBC.csv',
       'albumin', 'MAP', 'BMI']
meanFill(data, missing_values)

In [140]:
data.to_csv('result/final_tableV10.csv', index=False)